In [1]:
import pandas as pd

print(pd.__version__)

3.0.5

### SERIES

In [3]:
s = pd.Series([120, 85, 200, 45],
              index=["ene", "feb", "mar", "abr"],
              name="ventas")

print(s["mar"])       # acceso por etiqueta

200

In [4]:
print(s["abr"])

45

In [5]:
print(s * 1.21)       # vectorizado: IVA

ene    145.20
feb    102.85
mar    242.00
abr     54.45
Name: ventas, dtype: float64

In [9]:
s.mean()

np.float64(112.5)

In [10]:
s.max()

np.int64(200)

### DATAFRAME

In [23]:
import numpy as np

In [12]:
# a) Desde un diccionario de listas (la más habitual)
df = pd.DataFrame(
    {
        "producto": ["Laptop", "Monitor", "Teclado"],
        "unidades": [3, 7, 12],
        "precio":   [1200.0, 320.0, 95.0],
    }
)

print(df)

  producto  unidades  precio
0   Laptop         3  1200.0
1  Monitor         7   320.0
2  Teclado        12    95.0

In [16]:
df.head()

  producto  unidades  precio
0   Laptop         3  1200.0
1  Monitor         7   320.0
2  Teclado        12    95.0

In [17]:
# b) Desde una lista de diccionarios (típico de una API JSON)
df2 = pd.DataFrame(
    [
        {"producto": "Laptop", "unidades": 3},
        {"producto": "Monitor", "unidades": 7}
    ]
)

df2.head()

  producto  unidades
0   Laptop         3
1  Monitor         7

In [25]:
# c) Desde una lista de listas, indicando las columnas
df3 = pd.DataFrame(
    [
        ["Laptop", 3],
        ["Monitor", 7]
    ],
    columns=["producto", "unidades"]
)

df3.head()

  producto  unidades
0   Laptop         3
1  Monitor         7

In [24]:
# d) Desde un array de NumPy
df4 = pd.DataFrame(np.random.rand(3, 2), columns=["x", "y"])
df4.head()

          x         y
0  0.192684  0.519665
1  0.793891  0.922020
2  0.069816  0.887877

### CREACION DE COLUMNS

In [26]:
df

  producto  unidades  precio
0   Laptop         3  1200.0
1  Monitor         7   320.0
2  Teclado        12    95.0

In [28]:
df.shape

(3, 4)

In [27]:
df["importe"] = df["unidades"] * df["precio"]

print(df.shape)

(3, 4)

In [29]:
df.columns

Index(['producto', 'unidades', 'precio', 'importe'], dtype='str')

In [30]:
print(df.columns.tolist())

['producto', 'unidades', 'precio', 'importe']

In [32]:
df.head()

  producto  unidades  precio  importe
0   Laptop         3  1200.0   3600.0
1  Monitor         7   320.0   2240.0
2  Teclado        12    95.0   1140.0

In [33]:
df["dummy"] = 6

df.head()

  producto  unidades  precio  importe  dummy
0   Laptop         3  1200.0   3600.0      6
1  Monitor         7   320.0   2240.0      6
2  Teclado        12    95.0   1140.0      6

In [34]:
df["dummy2"] = [5, 4, 1]

df.head()

  producto  unidades  precio  importe  dummy  dummy2
0   Laptop         3  1200.0   3600.0      6       5
1  Monitor         7   320.0   2240.0      6       4
2  Teclado        12    95.0   1140.0      6       1

In [ ]:
# Crea una Series con las temperaturas [21, 24, 19, 27, 30] e índice de lunes a viernes.
temperaturas = pd.Series(
    [21, 24, 19, 27, 30],
    index=["Lunes", "Martes", "Miercoles", "Jueves", "Viernes"]
)

print(temperaturas)

# Muestra la media, el máximo y el día que corresponde al máximo (usa .idxmax()).
print("-"*100)
print("Media: ", temperaturas.mean())
print("Maximo: ", temperaturas.max())
print("Dia maximo: ", temperaturas.idxmax())
print("Dia maximo indice: ", temperaturas.argmax())
print("-"*100)

# Crea un DataFrame con 5 productos: nombre, categoría, stock y precio (inventados).
df = pd.DataFrame(
    {
        "nombre": ["Laptop", "Monitor", "Teclado", "Mouse", "Fuente de poder"],
        "categoria": ["Tecnologia", "Tecnologia", "Tecnologia", "Tecnologia", "Tecnologia"],
        "stock": [3, 7, 12, 1, 0],
        "precio":   [1200.0, 320.0, 95.0, 12.23, 90.8]
    }
)
df.head()

# Añade una columna valor_stock = stock × precio.
df["valor_stock"] = df["stock"] * df["precio"]
df.head()

# Imprime la forma del DataFrame y la lista de nombres de columna.
print(df.shape)

print(df.columns.to_list())

Lunes        21
Martes       24
Miercoles    19
Jueves       27
Viernes      30
dtype: int64
----------------------------------------------------------------------------------------------------
Media:  24.2
Maximo:  30
Dia maximo:  Viernes
Dia maximo indice:  4
----------------------------------------------------------------------------------------------------
(5, 5)
['nombre', 'categoria', 'stock', 'precio', 'valor_stock']

In [36]:
temperaturas.head()

Lunes        21
Martes       24
Miercoles    19
Jueves       27
Viernes      30
dtype: int64

### Read CSV

In [47]:
# /Users/marcell/Documents/codigo_by_tecsup/datascience-g8/data/ventas.csv
df = pd.read_csv("../data/ventas.csv")
df.head(n=10)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.0
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.0
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.0
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.1
5,2024-01-03,Oeste,Javier Sanz,Escritorio,Mobiliario,2,450,0.0
6,2024-01-03,Norte,Carlos Vega,Silla Ergo,Mobiliario,4,280,0.0
7,2024-01-03,Norte,Sofia Leon,Silla Ergo,Mobiliario,1,280,0.0
8,2024-01-03,Centro,Carlos Vega,Laptop Pro,Tecnologia,1,1200,0.1
9,2024-01-03,Centro,Pedro Diaz,Escritorio,Mobiliario,2,450,0.0

In [48]:
df.shape

(1200, 8)