In [52]:
import pandas as pd
# import numpy as np

df = pd.read_csv(
    "/Users/marcell/Documents/codigo_by_tecsup/datascience-g8/data/clientes_sucio.csv"
)

df.head(20)

,email,nombre,ciudad,fecha_nac,gasto_total,activo,telefono
0,ana.lopez@mail.com,Ana Lopez,MADRID,1985/04/12,"1.250,50",Si,+34 600111222
1,luis.perez@mail.com,luis perez,barcelona,1990-11-03,"890,00",si,600 222 333
2,MARTA.R@MAIL.COM,Marta Ruiz,Valencia,12/07/1978,"2.100,75",SI,NaN
3,pedro.diaz@mail.com,Pedro Diaz,madrid,1995-01-30,NaN,No,600-444-555
4,luis.perez@mail.com,luis perez,barcelona,1990-11-03,"890,00",si,600 222 333
5,sofia.leon@mail.com,Sofia Leon,SEVILLA,1988-06-21,"3.400,00",no,+34600666777
6,carlos.vega@mail.com,NaN,Bilbao,1992-09-14,"1.780,20",Si,NaN
7,elena.mora@mail.com,Elena Mora,madrid,1983/12/05,NaN,NO,600888999
8,javier.sanz@mail.com,Javier Sanz,Barcelona,1979-03-18,"5.600,00",si,600 999 000
9,lucia.ortiz@mail.com,Lucia Ortiz,valencia,2001-08-09,"430,10",No,600123456
10,MARTA.R@MAIL.COM,Marta Ruiz,Valencia,12/07/1978,"2.100,75",SI,NaN
11,miguel.cano@mail.com,Miguel Cano,Sevilla,1997-05-27,NaN,si,600654321

In [53]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   email        12 non-null     str
 1   nombre       11 non-null     str
 2   ciudad       12 non-null     str
 3   fecha_nac    12 non-null     str
 4   gasto_total  9 non-null      str
 5   activo       12 non-null     str
 6   telefono     9 non-null      str
dtypes: str(7)
memory usage: 804.0 bytes

In [43]:
df.shape

(12, 7)

In [44]:
df[ df.duplicated() ]

,email,nombre,ciudad,fecha_nac,gasto_total,activo,telefono
4,luis.perez@mail.com,luis perez,barcelona,1990-11-03,"890,00",si,600 222 333
10,MARTA.R@MAIL.COM,Marta Ruiz,Valencia,12/07/1978,"2.100,75",SI,NaN

In [45]:
clientes_sin_duplicados = df.drop_duplicates()
clientes_sin_duplicados.shape

(10, 7)

In [46]:
clientes_sin_duplicados.head(20)

,email,nombre,ciudad,fecha_nac,gasto_total,activo,telefono
0,ana.lopez@mail.com,Ana Lopez,MADRID,1985/04/12,"1.250,50",Si,+34 600111222
1,luis.perez@mail.com,luis perez,barcelona,1990-11-03,"890,00",si,600 222 333
2,MARTA.R@MAIL.COM,Marta Ruiz,Valencia,12/07/1978,"2.100,75",SI,NaN
3,pedro.diaz@mail.com,Pedro Diaz,madrid,1995-01-30,NaN,No,600-444-555
5,sofia.leon@mail.com,Sofia Leon,SEVILLA,1988-06-21,"3.400,00",no,+34600666777
6,carlos.vega@mail.com,NaN,Bilbao,1992-09-14,"1.780,20",Si,NaN
7,elena.mora@mail.com,Elena Mora,madrid,1983/12/05,NaN,NO,600888999
8,javier.sanz@mail.com,Javier Sanz,Barcelona,1979-03-18,"5.600,00",si,600 999 000
9,lucia.ortiz@mail.com,Lucia Ortiz,valencia,2001-08-09,"430,10",No,600123456
11,miguel.cano@mail.com,Miguel Cano,Sevilla,1997-05-27,NaN,si,600654321

In [47]:
clientes_sin_duplicados["email"] = clientes_sin_duplicados["email"].str.strip().str.lower()
clientes_sin_duplicados.head(20)

,email,nombre,ciudad,fecha_nac,gasto_total,activo,telefono
0,ana.lopez@mail.com,Ana Lopez,MADRID,1985/04/12,"1.250,50",Si,+34 600111222
1,luis.perez@mail.com,luis perez,barcelona,1990-11-03,"890,00",si,600 222 333
2,marta.r@mail.com,Marta Ruiz,Valencia,12/07/1978,"2.100,75",SI,NaN
3,pedro.diaz@mail.com,Pedro Diaz,madrid,1995-01-30,NaN,No,600-444-555
5,sofia.leon@mail.com,Sofia Leon,SEVILLA,1988-06-21,"3.400,00",no,+34600666777
6,carlos.vega@mail.com,NaN,Bilbao,1992-09-14,"1.780,20",Si,NaN
7,elena.mora@mail.com,Elena Mora,madrid,1983/12/05,NaN,NO,600888999
8,javier.sanz@mail.com,Javier Sanz,Barcelona,1979-03-18,"5.600,00",si,600 999 000
9,lucia.ortiz@mail.com,Lucia Ortiz,valencia,2001-08-09,"430,10",No,600123456
11,miguel.cano@mail.com,Miguel Cano,Sevilla,1997-05-27,NaN,si,600654321

In [48]:
clientes_sin_duplicados["nombre"] = clientes_sin_duplicados["nombre"].str.title()
clientes_sin_duplicados["ciudad"] = clientes_sin_duplicados["ciudad"].str.title()

clientes_sin_duplicados.head(20)

,email,nombre,ciudad,fecha_nac,gasto_total,activo,telefono
0,ana.lopez@mail.com,Ana Lopez,Madrid,1985/04/12,"1.250,50",Si,+34 600111222
1,luis.perez@mail.com,Luis Perez,Barcelona,1990-11-03,"890,00",si,600 222 333
2,marta.r@mail.com,Marta Ruiz,Valencia,12/07/1978,"2.100,75",SI,NaN
3,pedro.diaz@mail.com,Pedro Diaz,Madrid,1995-01-30,NaN,No,600-444-555
5,sofia.leon@mail.com,Sofia Leon,Sevilla,1988-06-21,"3.400,00",no,+34600666777
6,carlos.vega@mail.com,NaN,Bilbao,1992-09-14,"1.780,20",Si,NaN
7,elena.mora@mail.com,Elena Mora,Madrid,1983/12/05,NaN,NO,600888999
8,javier.sanz@mail.com,Javier Sanz,Barcelona,1979-03-18,"5.600,00",si,600 999 000
9,lucia.ortiz@mail.com,Lucia Ortiz,Valencia,2001-08-09,"430,10",No,600123456
11,miguel.cano@mail.com,Miguel Cano,Sevilla,1997-05-27,NaN,si,600654321

In [49]:
clientes_sin_duplicados["fecha_nac"] = pd.to_datetime(
    clientes_sin_duplicados["fecha_nac"],
    format="mixed",
    dayfirst=True
)
clientes_sin_duplicados

,email,nombre,ciudad,fecha_nac,gasto_total,activo,telefono
0,ana.lopez@mail.com,Ana Lopez,Madrid,1985-12-04,"1.250,50",Si,+34 600111222
1,luis.perez@mail.com,Luis Perez,Barcelona,1990-03-11,"890,00",si,600 222 333
2,marta.r@mail.com,Marta Ruiz,Valencia,1978-07-12,"2.100,75",SI,NaN
3,pedro.diaz@mail.com,Pedro Diaz,Madrid,1995-01-30,NaN,No,600-444-555
5,sofia.leon@mail.com,Sofia Leon,Sevilla,1988-06-21,"3.400,00",no,+34600666777
6,carlos.vega@mail.com,NaN,Bilbao,1992-09-14,"1.780,20",Si,NaN
7,elena.mora@mail.com,Elena Mora,Madrid,1983-05-12,NaN,NO,600888999
8,javier.sanz@mail.com,Javier Sanz,Barcelona,1979-03-18,"5.600,00",si,600 999 000
9,lucia.ortiz@mail.com,Lucia Ortiz,Valencia,2001-09-08,"430,10",No,600123456
11,miguel.cano@mail.com,Miguel Cano,Sevilla,1997-05-27,NaN,si,600654321

In [50]:
clientes_sin_duplicados["activo"] = clientes_sin_duplicados["activo"].str.lower().str.replace(
    {"si": "True", "no": "False"}
)

clientes_sin_duplicados.head(20)

,email,nombre,ciudad,fecha_nac,gasto_total,activo,telefono
0,ana.lopez@mail.com,Ana Lopez,Madrid,1985-12-04,"1.250,50",True,+34 600111222
1,luis.perez@mail.com,Luis Perez,Barcelona,1990-03-11,"890,00",True,600 222 333
2,marta.r@mail.com,Marta Ruiz,Valencia,1978-07-12,"2.100,75",True,NaN
3,pedro.diaz@mail.com,Pedro Diaz,Madrid,1995-01-30,NaN,False,600-444-555
5,sofia.leon@mail.com,Sofia Leon,Sevilla,1988-06-21,"3.400,00",False,+34600666777
6,carlos.vega@mail.com,NaN,Bilbao,1992-09-14,"1.780,20",True,NaN
7,elena.mora@mail.com,Elena Mora,Madrid,1983-05-12,NaN,False,600888999
8,javier.sanz@mail.com,Javier Sanz,Barcelona,1979-03-18,"5.600,00",True,600 999 000
9,lucia.ortiz@mail.com,Lucia Ortiz,Valencia,2001-09-08,"430,10",False,600123456
11,miguel.cano@mail.com,Miguel Cano,Sevilla,1997-05-27,NaN,True,600654321

In [51]:
clientes_sin_duplicados["telefono"] = clientes_sin_duplicados["telefono"].str.replace(r"\D", "", regex=True)
clientes_sin_duplicados

,email,nombre,ciudad,fecha_nac,gasto_total,activo,telefono
0,ana.lopez@mail.com,Ana Lopez,Madrid,1985-12-04,"1.250,50",True,34600111222
1,luis.perez@mail.com,Luis Perez,Barcelona,1990-03-11,"890,00",True,600222333
2,marta.r@mail.com,Marta Ruiz,Valencia,1978-07-12,"2.100,75",True,NaN
3,pedro.diaz@mail.com,Pedro Diaz,Madrid,1995-01-30,NaN,False,600444555
5,sofia.leon@mail.com,Sofia Leon,Sevilla,1988-06-21,"3.400,00",False,34600666777
6,carlos.vega@mail.com,NaN,Bilbao,1992-09-14,"1.780,20",True,NaN
7,elena.mora@mail.com,Elena Mora,Madrid,1983-05-12,NaN,False,600888999
8,javier.sanz@mail.com,Javier Sanz,Barcelona,1979-03-18,"5.600,00",True,600999000
9,lucia.ortiz@mail.com,Lucia Ortiz,Valencia,2001-09-08,"430,10",False,600123456
11,miguel.cano@mail.com,Miguel Cano,Sevilla,1997-05-27,NaN,True,600654321

In [57]:
clientes_sin_duplicados["telefono"] = clientes_sin_duplicados["telefono"].str.pad(3, fillchar="5")
clientes_sin_duplicados

,email,nombre,ciudad,fecha_nac,gasto_total,activo,telefono
0,ana.lopez@mail.com,Ana Lopez,Madrid,1985-12-04,"1.250,50",True,34600111222
1,luis.perez@mail.com,Luis Perez,Barcelona,1990-03-11,"890,00",True,600222333
2,marta.r@mail.com,Marta Ruiz,Valencia,1978-07-12,"2.100,75",True,NaN
3,pedro.diaz@mail.com,Pedro Diaz,Madrid,1995-01-30,NaN,False,600444555
5,sofia.leon@mail.com,Sofia Leon,Sevilla,1988-06-21,"3.400,00",False,34600666777
6,carlos.vega@mail.com,NaN,Bilbao,1992-09-14,"1.780,20",True,NaN
7,elena.mora@mail.com,Elena Mora,Madrid,1983-05-12,NaN,False,600888999
8,javier.sanz@mail.com,Javier Sanz,Barcelona,1979-03-18,"5.600,00",True,600999000
9,lucia.ortiz@mail.com,Lucia Ortiz,Valencia,2001-09-08,"430,10",False,600123456
11,miguel.cano@mail.com,Miguel Cano,Sevilla,1997-05-27,NaN,True,600654321

In [59]:
len("34600111222")

11

In [60]:
len("600222333")

9

In [61]:
clientes_sin_duplicados["telefono"].str.pad(15, fillchar="0")

0     000034600111222
1     000000600222333
2                 NaN
3     000000600444555
5     000034600666777
6                 NaN
7     000000600888999
8     000000600999000
9     000000600123456
11    000000600654321
Name: telefono, dtype: str