In [1]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/allisonhorst/palmerpenguins/main/inst/extdata/penguins.csv")
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007
...,...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009

In [2]:
df["species"].value_counts()

species
Adelie       152
Gentoo       124
Chinstrap     68
Name: count, dtype: int64

In [3]:
df["sex"].value_counts()

sex
male      168
female    165
Name: count, dtype: int64

In [4]:
df.head(5)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007

In [5]:
df.tail(8)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
336,Chinstrap,Dream,51.9,19.5,206.0,3950.0,male,2009
337,Chinstrap,Dream,46.8,16.5,189.0,3650.0,female,2009
338,Chinstrap,Dream,45.7,17.0,195.0,3650.0,female,2009
339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009

In [6]:
df.shape

(344, 8)

In [8]:
list(df.columns)

['species',
 'island',
 'bill_length_mm',
 'bill_depth_mm',
 'flipper_length_mm',
 'body_mass_g',
 'sex',
 'year']

In [9]:
df["species"].value_counts()

species
Adelie       152
Gentoo       124
Chinstrap     68
Name: count, dtype: int64

In [10]:
df["island"].value_counts()

island
Biscoe       168
Dream        124
Torgersen     52
Name: count, dtype: int64

In [12]:
filtrado = df[ (df["species"] == "Gentoo") & (df["body_mass_g"] > 5000)  ]
filtrado

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
153,Gentoo,Biscoe,50.0,16.3,230.0,5700.0,male,2007
155,Gentoo,Biscoe,50.0,15.2,218.0,5700.0,male,2007
156,Gentoo,Biscoe,47.6,14.5,215.0,5400.0,male,2007
159,Gentoo,Biscoe,46.7,15.3,219.0,5200.0,male,2007
161,Gentoo,Biscoe,46.8,15.4,215.0,5150.0,male,2007
...,...,...,...,...,...,...,...,...
267,Gentoo,Biscoe,55.1,16.0,230.0,5850.0,male,2009
269,Gentoo,Biscoe,48.8,16.2,222.0,6000.0,male,2009
273,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,male,2009
274,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,female,2009
275,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,male,2009

In [13]:
filtrado["species"].unique()

<StringArray>
['Gentoo']
Length: 1, dtype: str

In [14]:
filtrado["body_mass_g"].min()

np.float64(5050.0)

In [16]:
# cantidad, promedio, mínimo, máximo y desviación estándar.
agrupado = df.groupby("species")["body_mass_g"].agg([
    "count",
    "mean",
    "min",
    "max",
    "std"
])
agrupado

           count         mean     min     max         std
species
Adelie       151  3700.662252  2850.0  4775.0  458.566126
Chinstrap     68  3733.088235  2700.0  4800.0  384.335081
Gentoo       123  5076.016260  3950.0  6300.0  504.116237

In [23]:
# 27. Pingüino más pesado de cada especie
# Encuentra el registro correspondiente al pingüino con mayor body_mass_g dentro de cada especie. El
# resultado final debe mostrar species, sex, island y body_mass_g. No basta con mostrar únicamente la masa
# máxima: debes recuperar el registro completo correspondiente al máximo.


indices = df.groupby("species")["body_mass_g"].idxmax()

df.loc[indices]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
109,Adelie,Biscoe,43.2,19.0,197.0,4775.0,male,2009
313,Chinstrap,Dream,52.0,20.7,210.0,4800.0,male,2008
169,Gentoo,Biscoe,49.2,15.2,221.0,6300.0,male,2007

In [19]:
df.groupby("species")["body_mass_g"].max()

species
Adelie       4775.0
Chinstrap    4800.0
Gentoo       6300.0
Name: body_mass_g, dtype: float64

In [20]:
df.loc[109,:]

species              Adelie
island               Biscoe
bill_length_mm         43.2
bill_depth_mm          19.0
flipper_length_mm     197.0
body_mass_g          4775.0
sex                    male
year                   2009
Name: 109, dtype: object

In [21]:
df.loc[313, :]

species              Chinstrap
island                   Dream
bill_length_mm            52.0
bill_depth_mm             20.7
flipper_length_mm        210.0
body_mass_g             4800.0
sex                       male
year                      2008
Name: 313, dtype: object